#!/usr/bin/env python3
"""Genera 10 quizzes × 20 preguntas + 20 decks × 10 tarjetas de nivel doctoral
sobre el core de la tesis MRI-UTE, usando el conocimiento de los documentos
indexados. Inserta directamente en la BD (sin LLM, sin esperar)."""
import asyncio, sys, json, random
from datetime import date, timedelta
sys.path.insert(0, "/app")
from sqlalchemy import select
from estudio.db import SessionLocal
from estudio.models import Deck, Flashcard, Pregunta, Quiz, Tema
from estudio.rag.embeddings import embedir_passages

TEMA = "933ee140ea124c5a8aff1afb06c5d257"

# ════════════════════════════════════════════════════════════════════════
# QUIZZES (10 × 20 preguntas)
# ════════════════════════════════════════════════════════════════════════
# formato: (título, [preguntas])  pregunta = (enunciado, [alts], correcta_idx, explicación, archivo)

C = "MRI-UTE PROYECTO DE TESIS"
D = "defensa_tesis_doctoral"
P = "paper-mri-us"

QUIZZES = [
# ── Q1: Física de RM aplicada ──
("Examen Doctoral: Física de RM Aplicada a Tejidos con T2* Corto", [
 ("¿Por qué el T2* del hueso cortical es ultracorto (0.1–1 ms)?", ["Porque la densidad de protones es baja", "Porque el agua está ligada al colágeno y confinada en poros diminutos que aceleran el desfase", "Porque el campo B0 es bajo", "Porque el hueso es un tejido paramagnético"], 1, "El agua ligada al colágeno y confinada en poros nanométricos experimenta interacciones con superficies que aceleran el desfase de los espines, resultando en T2* de submilisegundo.", f"{D}/presentacion-especiales/relaxometria/guion_relaxometria.pdf"),
 ("¿Qué mide T2* frente a T2?", ["T2* incluye el desfase reversible por gradiente, T2 no", "T2* incluye el desfase irreversible por inhomogeneidades de campo B0, T2 solo el intrínseco del tejido", "Son sinónimos en tejidos biológicos", "T2* solo aplica a bajo campo"], 1, "T2* = T2 + desfase por ΔB₀ (inhomogeneidades locales). T2 es la relajación transversal intrínseca reversible; T2* la efectiva que incluye campos locales no deseados.", f"{D}/presentacion-especiales/relaxometria/guion_relaxometria.pdf"),
 ("¿Cuál es la relación entre M₀ y B₀?", ["M₀ ∝ √B₀", "M₀ ∝ B₀² ", "M₀ ∝ B₀ (la magnetización de equilibrio es proporcional al campo)", "M₀ es independiente de B₀"], 2, "La magnetización de equilibrio M₀ = N·γ²·ħ²·I(I+1)·B₀/(3kT): es linealmente proporcional a B₀. A 0.55 T, M₀ es ~35% de la de 1.5 T — de ahí el menor SNR del bajo campo.", f"{C}/narracion/texto/cap3.txt"),
 ("¿Qué es la constante giromagnética γ y cuál es su valor para protones?", ["La relación entre spin y momento magnético: γ ≈ 42.577 MHz/T", "La relación entre masa y carga: γ ≈ 1.6×10⁻¹⁹ C", "La velocidad de precesión: γ ≈ 2π rad/s", "El factor-g de Landé: γ ≈ 2.002"], 0, "γ = 42.577 MHz/T para protones de hidrógeno: relaciona el campo magnético con la frecuencia de Larmor f₀ = γ·B₀. A 0.55 T, f₀ ≈ 23.4 MHz.", f"{D}/codigo/plataforma/api_modelo_tricomponente/src/priors.py"),
 ("¿Por qué a mayor campo B₀ el T2* se acorta?", ["Porque la frecuencia de Larmor aumenta y amplifica el efecto de las inhomogeneidades ΔB₀", "Porque los espines precesan más rápido", "Porque la densidad de protones disminuye", "Porque la relajación T1 se acelera"], 0, "T2* ∝ 1/(γ·ΔB₀): a mayor B₀, las mismas inhomogeneidades relativas de susceptibilidad producen mayor desfase absoluto. Es la razón física de que a 0.55 T los pools se separen más temporalmente.", f"{D}/marco-teorico/bloque-B-fisica-resonancia-magnetica/T09-relajacion-T2-estrella.md"),
 ("¿Cuál es la frecuencia de Larmor a 0.55 T?", ["12.8 MHz", "23.4 MHz", "42.6 MHz", "63.9 MHz"], 1, "f₀ = γ·B₀ = 42.577 MHz/T × 0.55 T ≈ 23.4 MHz. De esta frecuencia se deriva el chemical shift: 3.5 ppm × 23.4 MHz = 82 Hz.", f"{D}/codigo/plataforma/api_modelo_tricomponente/src/priors.py"),
 ("¿Qué significa que el hueso cortical tenga ~15-20% de la densidad de protones del agua libre?", ["Que la señal de RM del hueso siempre será 15-20% del músculo", "Que solo el 15-20% del volumen del hueso contiene agua que produce señal de RM", "Que el T2* es 15-20% más corto que en agua", "Que el hueso absorbe el 80-85% de la señal"], 1, "El hueso es ~70% mineral (sin protones de RM) y solo el agua en la matriz y en poros produce señal. Esta baja densidad protónica, combinada con T2* ultracorto, es la razón de que el hueso sea invisible a RM convencional.", f"{C}/narracion/texto/cap3.txt"),
 ("¿Por qué la secuencia convencional de eco de gradiente no ve señal del hueso cortical?", ["Porque el hueso no contiene protones", "Porque el TE mínimo de ~2 ms es mayor que el T2* del bound water (~0.4 ms): la señal ya decayó a <1% de su valor", "Porque la resolución espacial es insuficiente", "Porque el hueso refleja la señal RF"], 1, "e^(-2/0.4) = e^(-5) < 1%: cuando el TE mínimo de la secuencia es 2 ms y el T2* es 0.4 ms, la señal ya desapareció antes de que la secuencia la mida. La UTE abre el ADC en 30 µs, antes del decaimiento.", f"{C}/narracion/texto/anexo1.txt"),
 ("¿Qué ventaja tiene el bajo campo 0.55 T frente a campo clínico para UTE en hueso?", ["Mayor SNR", "Menor susceptibilidad: T2* alargados y pools más separados temporalmente", "Mejor resolución espacial", "Menor tiempo de adquisición"], 1, "A 0.55 T, la menor susceptibilidad alarga los T2* asimétricamente: el bound water (más afectado por confinamiento) se alarga relativamente más. El resultado: los pools quedan MÁS separados, facilitando la descomposición.", f"{D}/marco-teorico/bloque-B-fisica-resonancia-magnetica/T09-relajacion-T2-estrella.md"),
 ("¿Cuál es el T2* del bound water a 1.5 T según Seifert 2015?", ["~40 µs", "~401 ± 119 µs", "~4 ms", "~40 ms"], 1, "Seifert 2015 reporta BW a 1.5 T = 401±119 µs, PW = 4110±1230 µs. A mayor campo, ambos se acortan. A 0.55 T se esperan alargados con mayor separación relativa.", f"{D}/marco-teorico/bloque-B-fisica-resonancia-magnetica/T09-relajacion-T2-estrella.md"),
 ("El T2* del pore water a 3 T según la tabla de Seifert es aproximadamente:", ["~389 µs", "~1300 µs (a 7 T)", "~4350 µs", "~886 µs (a 9.4 T)"], 1, "La tabla muestra que PW se acorta con el campo: 4110 µs a 1.5 T → 4350 µs a 3 T (con gran variabilidad) → 1300 µs a 7 T → 886 µs a 9.4 T. Esta es la base de la ventaja del bajo campo.", f"{D}/marco-teorico/bloque-B-fisica-resonancia-magnetica/T09-relajacion-T2-estrella.md"),
 ("¿Qué ventaja paradójica tiene trabajar a bajo campo para hueso cortical?", ["Menor costo del escáner", "Los pools de agua están MÁS separados temporalmente, facilitando la descomposición multi-exponencial", "Mejor contraste blando", "Mayor campo de visión"], 1, "A mayor campo, T2* se acorta por mayor ΔB₀, comprimiendo la separación entre pools. A 0.55 T ambos se alargan pero no igual: el BW (más afectado por confinamiento) se alarga relativamente más. Contraintuitivamente, el bajo campo facilita la separación.", f"{D}/marco-teorico/bloque-B-fisica-resonancia-magnetica/T09-relajacion-T2-estrella.md"),
 ("¿Cuál es la relación entre ΔB₀ y T2*?", ["T2* = T2 + 1/(γ·ΔB₀)", "T2* = T2 · ΔB₀", "T2* = T2 / ΔB₀", "No hay relación"], 0, "T2* es inversamente proporcional a γ·ΔB₀: mayor inhomogeneidad de campo, mayor desfase y T2* más corto. La relación exacta depende de la distribución espacial de ΔB₀ ( Lorentziana, Gaussiana, etc.).", f"{D}/marco-teorico/bloque-B-fisica-resonancia-magnetica/T09-relajacion-T2-estrella.md"),
 ("¿Qué es la desfosforilación en el contexto de RM?", ["La pérdida de señal por movimiento", "No es un término de RM: es un error de la pregunta", "La relajación longitudinal T1", "El desfase por susceptibilidad"], 1, "Esta es una pregunta de control de atención del comité: desfosforilación es un término bioquímico, no de física de RM. El desfase relevante para UTE es por T2* ultracorto.", f"{C}/narracion/texto/cap3.txt"),
 ("¿Por qué el pulmón también requiere secuencias UTE?", ["Porque tiene baja densidad de protones", "Porque la interfase aire-tejido crea diferencias de susceptibilidad que aceleran el desfase", "Porque es un órgano móvil", "Porque contiene hierro paramagnético"], 1, "La interfase aire-tejido pulmonar crea grandes diferencias de susceptibilidad magnética locales que aceleran el desfase igual que el confinamiento nanométrico del hueso. La misma física motiva la misma solución: TE ultracorto.", f"{C}/narracion/texto/cap3.txt"),
 ("¿Cuál es el rango de T2* del bound water reportado en la literatura?", ["5–50 µs", "50–500 µs (0.02–1 ms)", "5–50 ms", "50–500 ms"], 1, "BW tiene T2* de 50-500 µs según la escala de confinamiento. A 0.55 T se espera alargado hacia el extremo superior del rango (~0.5-1 ms).", f"{D}/presentacion-especiales/relaxometria/guion_relaxometria.pdf"),
 ("¿Cuál es el rango de T2* del pore water?", ["50–500 µs", "0.1–1 ms", "1–50 ms (3–20 ms reportado)", "50–500 ms"], 2, "PW tiene T2* de 1-50 ms gobernado por la escala del poro: canales de Havers (~50 µm) y sistemas lacunocaniculares (~100 nm - ~10 µm). Es el pool que se asocia a porosidad y fragilidad.", f"{D}/presentacion-especiales/relaxometria/guion_relaxometria.pdf"),
 ("Los tres pools de protones del hueso cortical difieren en T2* aproximadamente por un factor de:", ["2×", "10×", "100× entre pools vecinos", "1000×"], 2, "Los T2* difieren ~100× entre pools vecinos: BW ~0.4 ms, PW ~4 ms, BM ~40 ms. Esta separación es lo que hace posible (en principio) descomponer la señal multi-exponencialmente.", f"{D}/presentacion-especiales/relaxometria/guion_relaxometria.pdf"),
 ("¿Qué resonador se usa en esta tesis y con qué bobina?", ["3 T Siemens Skyra con bobina de cabeza", "0.55 T MAGNETOM Free.Max con bobina flexible de extremidad", "1.5 T Philips Ingenia con bobina de cuerpo", "7 T Bruker con bobina de rodilla"], 1, "El MAGNETOM Free.Max de 0.55 T (Siemens Healthineers) es un resonador de cuerpo completo de bajo campo. La bobina flexible de extremidad maximiza la señal cerca de la corteza tibial.", f"{C}/capitulos/capitulo4.tex"),
 ("¿Por qué se eligió la bobina flexible de extremidad en lugar de una de cuerpo completo?", ["Porque es más cómoda para el paciente", "Porque tiene mejor sensibilidad local cerca de la tibia, compensando en parte el menor SNR del bajo campo", "Porque es más barata", "Porque es la única compatible con 0.55 T"], 1, "Una bobina colocada cerca de la tibia tiene mayor sensibilidad local que una de cuerpo. El SNR adicional compensa parcialmente la menor magnetización de equilibrio M₀ ∝ B₀ del bajo campo.", f"{C}/capitulos/capitulo4.tex"),
]),

# ── Q2: Secuencia UTE 2D ──
("Examen Doctoral: Secuencia UTE 2D — Half Pulse, VERSE y Ramp Sampling", [
 ("¿Qué es un half pulse en UTE y por qué se usan dos?", ["Un pulso de mitad de amplitud para ahorrar energía; se usan dos por seguridad", "Cada medio pulso excita la mitad del plano; dos con gradiente de corte de polaridad invertida completan el perfil de excitación", "Un pulso de mitad de duración para acortar el TE; dos porque la secuencia es 2D", "Un pulso de media frecuencia; dos para cubrir todo el ancho de banda"], 1, "Un pulso selectivo completo de corte tomaría milisegundos (imposible para TE=30µs). Cada half pulse deja fase residual en k_z, pero dos con gradiente invertido suman el perfil completo. La clave: el remapeo VERSE asegura que cada excitación termina en k_z=0.", f"{C}/narracion/texto/anexo1.txt"),
 ("¿Qué es VERSE (Variable-Rate Selective Excitation)?", ["Una técnica de supresión de grasa", "Un remapeo de la amplitud B₁ del pulso RF sobre la forma del gradiente que acorta la duración efectiva manteniendo el flip angle", "Un método de reconstrucción iterativa", "Una forma de reducir el SAR"], 1, "VERSE: B̃₁(t) = B₁(t)·G_z(t)/G̃_z(t). Redistribuye la energía del pulso sobre la rampa del gradiente, manteniendo la integral (flip angle) pero acortando la duración. En la tesis, el remapeo VERSE-like replica la lógica de MATLAB.", f"{C}/codigo/plataforma/api_generacion_ute/src/crearPulsoSeleccionCorte.py"),
 ("¿Qué parámetros tiene el pulso de selección de corte en esta tesis?", ["Flip 90°, TBW=4, duración 1 ms, corte 5 mm", "Flip 30°, TBW=2, duración 0.5 ms, corte 10 mm", "Flip 45°, TBW=1, duración 2 ms, corte 15 mm", "Flip 60°, TBW=3, duración 0.8 ms, corte 8 mm"], 1, "El pulso sinc apodizado tiene flip angle de 30°, TBW=2, duración de 0.5 ms y grosor de corte de 10 mm. El gradiente se fija como G_z = BW/(γ·Δz).", f"{D}/presentacion-especiales/secuencia-ute/scripts/gen_guion.py"),
 ("¿Qué es ramp sampling en UTE?", ["Muestrear solo la meseta del gradiente para máxima señal", "Muestrear durante la rampa del gradiente, abriendo el ADC inmediatamente después del fin de la RF", "Adquirir múltiples rampas por TR para mayor SNR", "Una técnica de reconstrucción para datos de rampa"], 1, "El ADC abre mientras el gradiente sube de cero a su amplitud máxima: la trayectoria k(t) no es lineal durante la subida. Es lo que define el TE mínimo de 30 µs. La NUFFT debe recibir los tiempos exactos cuantizados al raster del ADC.", f"{C}/capitulos/capitulo4.tex"),
 ("¿Por qué la trayectoria radial centro-fuera es óptima para UTE?", ["Solo por simplicidad de implementación", "Porque empieza en k=0 (compatible con TE corto), no requiere refocusing, es robusta al movimiento, sobremuestrea el centro del contraste, y con ángulos aleatorios da la incoherencia que CS necesita", "Porque es la única compatible con Pypulseq", "Porque consume menos tiempo de computación"], 1, "Cinco razones estratégicas: (1) empieza en k=0 compatible con TE ultra-corto, (2) sin refocusing ahorra ~1 ms, (3) robustez al movimiento, (4) sobremuestreo del centro donde vive el contraste, (5) con ángulos aleatorios regala la incoherencia para CS.", f"{D}/marco-teorico/bloque-C-fisica-secuencia-ute/T14-trayectoria-radial.md"),
 ("¿Cómo se proyecta el gradiente de lectura para un radio en ángulo φ?", ["Se usa un gradiente distinto para cada radio", "Se reparte el mismo trapezoide: Gx = G·cosφ y Gy = G·sinφ", "Se alterna entre ejes x e y", "Se usa solo el eje x siempre"], 1, "Basta repartir el mismo trapezoide entre los dos ejes según el ángulo. Cambiar de radio es cambiar dos amplitudes (Gx, Gy), no rediseñar la secuencia. Es una observación económica clave defendible en el comité.", f"{D}/presentacion-especiales/secuencia-ute/guion_secuencia_ute.pdf"),
 ("¿Cuál es el TE mínimo alcanzado y cómo se mide?", ["30 µs, desde el inicio del pulso RF hasta el centro del ADC", "30 µs, desde el fin del pulso RF hasta la primera muestra del ADC", "8 µs, desde el fin de la RF", "50 µs, desde el inicio de la rampa"], 1, "TE = 30 µs se verifica desde el fin del pulso RF hasta la primera muestra del ADC. Es el parámetro crítico de la secuencia: define si la señal de T2* ultracorto es capturada antes de decaer.", f"{C}/anexos/anexo2.tex"),
 ("¿Qué es el spoiling de RF con incremento de 117°?", ["Un pulso de inversión para suprimir grasa", "Una progresión aritmética de fase del RF y ADC que destruye la magnetización residual entre TRs", "Un cambio de frecuencia para evitar aliasing", "Una técnica de corrección de B0"], 1, "El RF spoiling con incremento de 117° asigna una fase incrementalmente variable al pulso de RF y al ADC para que la magnetización residual no se re-adicione coherente entre disparos. Sin spoiling, el modelo lineal y=Ex dejaría de describir el dato.", f"{C}/main.pdf"),
 ("¿Qué es el spoiler de gradiente en UTE radial?", ["Un gradiente de reenfoque para corregir la fase", "Un gradiente al 20% de amplitud máxima, rotado en la dirección del radio, que destruye la coherencia residual al final de cada lectura", "Un gradiente de difusión", "Un gradiente de flujo"], 1, "Cada lectura radial cierra con un spoiler de gradiente en el plano de lectura, rotado en la misma dirección del radio, con amplitud del 20% del máximo del sistema y duración acotada por el tiempo disponible del TR.", f"{C}/main.pdf"),
 ("¿Qué es el teorema de Nyquist radial y cuántos radios exige?", ["π·Nx radios para cobertura completa sin aliasing en 2D", "2·Nx radios", "Nx² radios", "Nx/2 radios"], 0, "El teorema de Nyquist radial establece que para evitar aliasing en muestreo radial 2D se necesitan al menos π·Nx radios (o π·Nx/2 TRs con 2 spokes/TR). Si se viola, aparecen artefactos en estrella.", f"{D}/marco-teorico/bloque-C-fisica-secuencia-ute/T15-nyquist-radial.md"),
 ("¿Cuál es el valor de Nx en esta tesis y qué implica?", ["Nx = 256: resolución estándar clínica", "Nx = 500: incorpora el sobremuestreo radial y es la base del criterio de Nyquist π·Nx", "Nx = 128: adquisición rápida", "Nx = 1024: alta resolución"], 1, "Nx = 500 incorpora el sobremuestreo radial (denso cerca del centro). El número de radios parte de Nyquist π·500 ≈ 1571 (o ~785 TRs con 2 spokes/TR) y se multiplica por el factor de submuestreo CS.", f"{D}/marco-teorico/bloque-C-fisica-secuencia-ute/T15-nyquist-radial.md"),
 ("¿Cómo se calcula k_max y contra qué se verifica?", ["k_max = G·TR, se verifica contra Nx", "k_max = 2π·G·t_eff (meseta + mitad de rampas), se verifica contra k_teórico = π·Nx/FOV", "k_max = γ·B₀, se verifica contra la frecuencia de Larmor", "k_max = BW/(γ·Δz)"], 1, "k_max = 2π·G·t_eff donde t_eff = meseta + mitad de rampas. Se verifica contra el límite teórico π/Δx = π·Nx/FOV. Si k_max excede, se reajusta la amplitud del gradiente. Así la resolución queda acotada por diseño.", f"{D}/presentacion-especiales/secuencia-ute/guion_secuencia_ute.pdf"),
 ("¿Qué es el cuantizado al raster del ADC y por qué es importante?", ["Redondear los tiempos de la secuencia a múltiplos del dwell time del ADC para sincronización exacta", "Aumentar la resolución del ADC", "Reducir el ruido del cuantizador", "Ajustar la ganancia del receptor"], 0, "t_k^q = round(t_k/Δt_ADC)·Δt_ADC: garantiza que la trayectoria k(t) que la NUFFT usa en E coincida con la realmente ejecutada por el escáner. Sin esta disciplina temporal, habría desalineación sistemática del centro del k-space.", f"{C}/capitulos/capitulo9.tex"),
 ("¿Qué framework se usa para implementar la secuencia UTE?", ["MATLAB + IDEA (proprietario Siemens)", "Pypulseq (open-source Python, compila a archivo .seq ejecutable por Siemens)", "GNU Radio", "LabVIEW"], 1, "Pypulseq permite definir programáticamente pulsos RF, gradientes y eventos ADC que se compilan a un archivo .seq ejecutable por el escáner Siemens. Un mismo núcleo científico sirve a la simulación (KomaMRI) y al escáner real.", f"{C}/narracion/texto/anexo2.txt"),
 ("¿Qué simulador valida la secuencia antes del escáner real?", ["BlochSolver", "KomaMRI (Julia)", "Simulink", "COMSOL"], 1, "KomaMRI resuelve las ecuaciones de rotación de Bloch para cada voxel, validando que la secuencia produce la señal esperada. Se verifica: timing de eventos, fidelidad de trayectoria, respuesta para diferentes T1/T2*/densidad protónica.", f"{C}/capitulos/capitulo5.tex"),
 ("¿Qué es un dummy scan y para qué sirve en UTE?", ["Un escaneo de calibración para el B0 map", "Adquisiciones iniciales sin datos para estabilizar el estado estacionario antes de la adquisición real", "Un escaneo de referencia para el registro", "Un escaneo de control de calidad"], 1, "Los dummy scans son excitaciones iniciales que no guardan datos: permiten que la magnetización llegue al estado estacionario antes de comenzar la adquisición productiva. Sin ellos, los primeros radios tendrían señal anómala.", f"{C}/narracion/texto/anexo2.txt"),
 ("¿Qué ventaja tiene la secuencia radial frente a la cartesiana en UTE (además del TE corto)?", ["Mayor resolución", "Cada radio es independiente y cruza el centro: robustez al movimiento + sobremuestreo central del contraste", "Menor SAR", "Menor tiempo de reconstrucción"], 1, "Cada radio atraviesa el centro del k-space donde se concentra el contraste, y cada uno es una adquisición independiente: si el paciente se mueve, solo se corrompen los radios afectados, no toda la imagen como en cartesiano.", f"{D}/marco-teorico/bloque-C-fisica-secuencia-ute/T14-trayectoria-radial.md"),
 ("¿Cuál es la diferencia entre UTE y ZTE (Zero Echo Time)?", ["ZTE tiene mejor resolución; UTE es más rápido", "UTE usa un pulso truncado seguido de lectura radial; ZTE excita con el gradiente ya encendido (TE virtualmente cero) pero con menos flexibilidad para CS", "UTE es 2D; ZTE es 3D siempre", "No hay diferencia práctica"], 1, "ZTE tiene TE virtualmente cero (excita durante el gradiente) pero limitaciones: dead time del transmisor/receptor, menos flexibilidad en el patrón de muestreo para CS. La tesis eligió UTE por compatibilidad con Pypulseq, CS con ángulos aleatorios, y control fino del TE.", f"{C}/narracion/texto/cap3.txt"),
 ("¿Qué es el factor de submuestreo CS y qué rango soporta el protocolo?", ["cs_undersampling_factor ∈ [0, 1]: 0.2 a 1.0 (5× a 1×)", "El factor va de 1 a 10", "Solo soporta factor 0.5 (2×)", "Es un número fijo en 0.3"], 0, "cs_undersampling_factor ∈ [0.2, 1.0]: multiplica el número de radios de Nyquist. Con factor 1.0 fuerza barrido secuencial uniforme; con factor menor, sortea ángulos aleatorios ~U[0,2π) con semilla fija para reproducibilidad.", f"{C}/anexos/anexo2.tex"),
 ("¿Por qué la excitación debe terminar en k_z = 0?", ["Para maximizar la señal", "Para que no haya fase de corte por refocalizar: el ADC puede abrir inmediatamente sin gradiente de reenfoque, logrando TE = 30 µs", "Para evitar artefactos de aliasing", "Porque el escáner lo exige"], 1, "Si la excitación termina en k_z ≠ 0, habría fase residual de corte que requeriría un gradiente de reenfoque (tomando tiempo y alargando el TE). Con k_z = 0 (garantizado por VERSE), el ADC abre inmediatamente después del fin de la RF.", f"{C}/narracion/texto/anexo1.txt"),
]),

# ── Q3: Reconstrucción por CS ──
("Examen Doctoral: Reconstrucción por Compressed Sensing en UTE", [
 ("¿Cuál es el modelo de medición del problema inverso en RM?", ["y = x + n", "y = E·x + n, donde E es el operador de adquisición, x la imagen, y los datos, n el ruido", "x = E⁻¹·y", "y = F(x) donde F es no lineal"], 1, "y = E·x + n: los datos y son el operador E aplicado a la imagen x, más ruido η. Con submuestreo CS (M ≪ N), E tiene núcleo no trivial: Ex = y tiene infinitas soluciones. CS decide cuál imagen quedarse.", f"{D}/presentacion-especiales/compressed-sensing/guion_compressed_sensing.pdf"),
 ("¿Cómo se factoriza el operador E en la reconstrucción radial?", ["E = C · F · D (sensibilidades, Fourier, densidad)", "E = D^½ · F_NUFFT · C (raíz de densidad, Fourier no uniforme, sensibilidades)", "E = F · G · S (Fourier, gradiente, señal)", "E = A · Σ · Vᵀ (SVD)"], 1, "E = D^½ · F_NUFFT · C, leído de derecha a izquierda: C son las sensibilidades de bobina, F_NUFFT la Fourier no uniforme, D^½ la raíz de la compensación de densidad. Su adjunto E^H = C^H·NUFFT^H·D^½ es la retroproyección.", f"{D}/presentacion-especiales/compressed-sensing/guion_compressed_sensing.pdf"),
 ("¿Por qué la compensación de densidad D es necesaria en radial?", ["Para corregir el movimiento del paciente", "Porque todos los radios cruzan el centro del k-space sobremuestreándolo: la densidad va como 1/|k| y D reequilibra", "Para reducir el ruido gaussiano", "Para acelerar la reconstrucción"], 1, "La densidad de muestreo radial va como 1/|k|: el centro está sobremuestreado. D son pesos diagonales (método iterativo de Pipe-Menon, w ← w/(Gw)) que reequilibran. D^½ blanquea el residuo ℓ2 para que sea estadísticamente correcto.", f"{D}/presentacion-especiales/compressed-sensing/guion_compressed_sensing.pdf"),
 ("¿Cuál es el funcional de optimización de la reconstrucción CS?", ["min ‖x‖² + λ‖y‖²", "min (1/2)‖E·x − y‖²₂ + λ·TV(x), con λ = 10⁻⁴", "min ‖x‖₁ + λ‖E·x‖₂", "max P(x|y) sin restricciones"], 1, "x̂ = argmin (1/2)‖E·x−y‖²₂ + λ·TV(x): el primer término es fidelidad a los datos, el segundo el regularizador TV. λ = 10⁻⁴ en esta tesis, calibrado en fantoma y validado con métricas pareadas.", f"{C}/main.pdf"),
 ("¿Por qué se usa Variación Total en lugar de ℓ1 sobre wavelets?", ["Porque es computacionalmente más barato", "Porque TV promueve imágenes suaves por partes preservando bordes — exactamente la estructura del hueso cortical", "Porque wavelets no funcionan en 2D", "Porque es la única compatible con ADMM"], 1, "TV(x) = Σ‖∇x‖₁ es la norma ℓ1 del gradiente: un borde nítido (un salto grande) es barato, muchos saltos pequeños (ruido, streaks) son caros. La cortical es una región homogénea con borde fino: el prior anatómico correcto.", f"{D}/marco-teorico/bloque-F-reconstruccion/T31-compressed-sensing.md"),
 ("¿Qué solver se usa y cuántas iteraciones?", ["L-BFGS, 100 iteraciones", "ADMM (Alternating Direction Method of Multipliers), 50 iteraciones", "Gradient descent, 1000 iteraciones", "Newton, 10 iteraciones"], 1, "TV no es diferenciable en el origen → ADMM la maneja a través de su operador proximal. Repite pequeñas correcciones 50 veces hasta que la imagen cumple consistencia con los datos + suavidad por tramos.", f"{C}/main.pdf"),
 ("¿Cuál es la condición 1 para que CS funcione?", ["La imagen debe ser pequeña en tamaño", "La señal debe ser esparsa en algún dominio (gradient, wavelet)", "El ruido debe ser gaussiano", "El k-space debe ser cartesiano"], 1, "Condición 1: esparsidad. La imagen debe tener una representación escasa en algún dominio Ψ. TV explota que el gradiente de la imagen cortical es disperso: pocas transiciones grandes (bordes) y muchas celdas uniformes.", f"{D}/marco-teorico/bloque-F-reconstruccion/T31-compressed-sensing.md"),
 ("¿Cuál es la condición 2 (incoherencia) y por qué el radial la satisface?", ["El muestreo debe ser uniforme; el radial es uniforme", "El aliasing debe parecer ruido difuso, no anatomía; el radial con ángulos aleatorios produce aliasing incoherente", "La señal debe ser coherente con el ruido", "El teorema de Nyquist debe cumplirse"], 1, "Submuestrear siempre genera error. Lo que decide si es eliminable es su aspecto: si parece ruido difuso (incoherente), ℓ1 lo separa; si parece anatomía (coherente, ghosting cartesiano), es irrecuperable. El radial con ángulos ~U[0,2π) produce aliasing incoherente.", f"{D}/presentacion-especiales/compressed-sensing/guion_compressed_sensing.pdf"),
 ("¿Cuál es la aceleración típica CS aceptable en RM sin artefactos visibles?", ["Hasta 2×", "Hasta 5× (20% de muestras) con buena regularización; >6× produce artefactos", "Hasta 10×", "Hasta 20×"], 1, "La tabla de aceleración: 2× excelente (50%), 3× muy buena (33%), 4× buena (25%), 5× aceptable con buena regularización (20%), >6× artefactos visibles (<17%). El protocolo soporta cs_undersampling_factor ∈ [0.2, 1.0].", f"{D}/marco-teorico/bloque-F-reconstruccion/T31-compressed-sensing.md"),
 ("¿Por qué se normaliza el k-space de cada eco antes de la reconstrucción?", ["Para reducir el ruido", "Porque TV es homogénea de grado 1 y el término de datos de grado 2: sin normalizar, el peso relativo de la regularización crece al decaer la señal, sesgando la curva de decaimiento", "Para acelerar el ADMM", "Para corregir el movimiento"], 1, "La normalización por eco compensa el efecto de que TV (grado 1) y el término de datos (grado 2) escalan distinto: sin ella, los ecos tardíos (señal baja) quedan sobre-regularizados, inclinando la curva de decaimiento y sesgando T2*.", f"{D}/Paper-MRI-US/Content/3_Methods.tex"),
 ("¿Qué es la propiedad RIP (Restricted Isometry Property)?", ["Una propiedad del gradiente de la imagen", "El operador de medición debe preservar aproximadamente las normas de todas las señales esparsas: garantiza que las muestras contienen la información sin distorsión direccional", "Una condición sobre el ruido gaussiano", "El requerimiento de que E sea invertible"], 1, "RIP formaliza que las pocas muestras tomadas contienen la información de la señal esparsa sin distorsión direccional. Junto a la incoherencia µ(E), da las cotas de recuperación de Candès-Tao: con suficiente incoherencia y esparsidad k, ℓ1 recupera la señal.", f"{D}/marco-teorico/bloque-F-reconstruccion/T31-compressed-sensing.md"),
 ("¿Cómo se elige λ en la práctica?", ["λ = 1 siempre", "λ se ajusta empíricamente por L-curve, discrepancia (residuo = ruido esperado) o validación visual", "λ es fijo en 0.5", "λ no importa en CS"], 1, "λ pequeño → imagen ruidosa con aliasing. λ grande → imagen sobre-suavizada. Métodos: L-curve (rodilla en la gráfica ‖Ex-y‖ vs TV(x)), discrepancia (residuo coincide con ruido esperado), validación visual. En la tesis: λ = 10⁻⁴ calibrado en fantoma.", f"{D}/marco-teorico/bloque-F-reconstruccion/T32-variacion-total.md"),
 ("¿Por qué el cartesiano uniforme NO funciona para CS?", ["Porque es más lento", "Porque produce réplicas periódicas (ghosting) que son indistinguibles de anatomía real: aliasing coherente irrecuperable", "Porque no soporta ADMM", "Porque el k-space cartesiano es siempre completo"], 1, "Saltarse líneas regulares en cartesiano produce réplicas periódicas de la imagen (ghosting clásico). Una réplica desplazada es indistinguible de estructura anatómica real: la coherencia mutua µ(E) entre patrón y base es máxima, y ningún algoritmo puede separar.", f"{D}/presentacion-especiales/compressed-sensing/guion_compressed_sensing.pdf"),
 ("¿Qué framework se usa para la reconstrucción CS?", ["MATLAB con la toolbox ISMRM", "TensorFlow-MRI (tfmri): NUFFT, operadores de sensibilidad y optimizadores proximales componibles", "PyTorch con SigPy", "C++ custom"], 1, "La reconstrucción avanzada usa TensorFlow-MRI: expone NUFFT, operadores de sensibilidad y optimizadores proximales como bloques componibles. El mismo pipeline corre en simulación y en la campaña in vivo.", f"{C}/docs/template-parcial-final-2026-09-19.pdf"),
 ("¿En qué sentido la reconstrucción CS es un estimador MAP?", ("Porque minimiza el error cuadrático medio", "Porque el funcional (1/2)‖Ex−y‖² + λ·TV(x) es exactamente −log verosimilitud (ruido gaussiano) − log prior (Laplaciano del gradiente): minimizar = maximizar la probabilidad a posteriori", "Porque usa el máximo de la distribución a priori", "Porque asume ruido Poisson"), 1, "El funcional es exactamente −log L(ruido gaussiano) − log p(prior Laplaciano sobre el gradiente). Minimizarlo equivale a maximizar P(x|y): la imagen más probable dado el dato y el prior. La regularización es inferencia bayesiana explícita.", f"{D}/presentacion-especiales/compressed-sensing/guion_compressed_sensing.pdf"),
 ("¿Qué es el suavizado de Huber y por qué se usa en TV?", ("Una forma de aproximar la norma ℓ2", "Reemplaza la cúspide de ℓ1 en el origen por un tramo cuadrático, haciendo TV diferenciable en cero y habilitando métodos de gradiente tipo L-BFGS", "Un método de interpolación", "Un filtro de suavizado espacial"), 1, "TV no es suave en el origen. Huber la reemplaza por un tramo cuadrático local: idéntica a ℓ1 para valores grandes pero diferenciable en cero. Esto permite usar L-BFGS sin oscilaciones numéricas cerca del mínimo. Con parámetro de transición pequeño para no alterar el prior.", f"{D}/presentacion-especiales/compressed-sensing/scripts/gen_guion.py"),
 ("¿Cómo se determinan los ángulos de adquisición en modo CS?", ("Secuenciales uniformes siempre", "Se sortean ~U[0,2π) con semilla fija para reproducibilidad: la distribución es incoherente pero reproducible bit a bit", "Ángulo áureo (golden angle)", "Espaciados logarítmicamente"), 1, "Los ángulos se sortean uniformes en [0,2π) con semilla fija (random_seed=42 en el código). Con factor 1.0 se fuerza barrido secuencial uniforme de Nyquist. La semilla fija garantiza reproducibilidad: re-adquirir produce el mismo patrón k-space.", f"{C}/anexos/anexo2.tex"),
 ("¿Por qué solo 10 iteraciones de L-BFGS (pregunta de defensa)?", ("Por limitación de tiempo de cómputo", "Porque la mayor ganancia de calidad ocurre en las primeras iteraciones y el residual restante es comparable al ruido: más iteraciones ajustarían ruido, no señal", "Porque el hardware no permite más", "Porque es un valor empírico sin justificación"), 1, "Para este nivel de submuestreo, la mayor ganancia ocurre en las primeras iteraciones. El residual restante es comparable al ruido del dato: iterar más empieza a ajustar ruido (sobre-ajuste). Las curvas de métrica vs iteración se aplanan alrededor de esa cuenta.", f"{D}/presentacion-especiales/compressed-sensing/guion_compressed_sensing.pdf"),
 ("¿Qué framework alternativo a SENSE se descartó y por qué?", ("GRAPPA: requiere multi-bobina", "SENSE: solo funciona con submuestreo cartesiano regular de factor entero R, no con radial aleatorio", "Compressed Sensing: no funciona en radial", "Regridding: es demasiado lento"), 1, "SENSE desenreda píxeles plegados con sensibilidades pero solo con submuestreo cartesiano regular. El radial con ángulos aleatorios no produce plegamiento desenredable por SENSE: exige el enfoque CS. Además SENSE sufre g-factor (amplificación de ruido).", f"{D}/marco-teorico/bloque-F-reconstruccion/T33-metodos-reconstruccion.md"),
 ("La aceleración CS también reduce el tiempo de examen. ¿Qué factor del protocolo soporta?", ("Solo 1× (sin aceleración)", "De 1× (factor 1.0, Nyquist completo) a 5× (factor 0.2, 20% de muestras)", "Solo 2×", "10×"), 1, "El protocolo soporta cs_undersampling_factor ∈ [0.2, 1.0] que equivale a aceleraciones de 1× (completo) a 5× (20% de muestras). Con 5×, un protocolo de ~785 TRs se reduce a ~157: de ~13 min a ~2.6 min.", f"{D}/marco-teorico/bloque-F-reconstruccion/T31-compressed-sensing.md"),
]),

# ── Q4: Relaxometría tri-componente ──
("Examen Doctoral: Relaxometría T2* Tri-componente con Ancla de Médula", [
 ("¿Cuál es el modelo de señal tricomponente del hueso cortical?", ("S(TE) = S₀·e^(-TE/T2)", "S(TE) = S₀·|f_bw·e^(-TE/T2*,bw) + f_pw·e^(-TE/T2*,pw) + f_bm·e^(-TE/T2*,bm)·e^(j2πΔf·TE)|", "S(TE) = S₁·e^(-TE/T₂₁) + S₂·e^(-TE/T₂₂)", "S(TE) = S₀·(1-e^(-TE/T1))"), 1, "El modelo tricomponente: magnitud de una suma compleja de tres exponenciales ponderadas por fracciones, con Σf=1. El término de médula lleva la fase química e^(j2πΔf·TE) con Δf≈82 Hz a 0.55 T. Los dos primeros (agua) van en fase.", f"{D}/presentacion-especiales/relaxometria/guion_relaxometria.pdf"),
 ("¿Cuál es el valor de Δf (chemical shift agua-grasa) a 0.55 T y cómo se calcula?", ("42 Hz; 1 ppm × 42.577 MHz/T × 0.55 T", "82 Hz; 3.5 ppm × 42.577 MHz/T × 0.55 T = 81.96 Hz", "100 Hz; valor empírico", "3.5 Hz; directamente de la literatura"), 1, "La grasa resuena a 3.5 ppm del agua. A 0.55 T: f₀ = γ·B₀ = 42.577 MHz/T × 0.55 T ≈ 23.4 MHz. Δf = 3.5 ppm × 23.4 MHz = 81.96 Hz ≈ 82 Hz. En priors.py está documentado como DF_QUIMICO_HZ_DEFECTO.", f"{D}/codigo/plataforma/api_modelo_tricomponente/src/priors.py"),
 ("¿Por qué el modelo tricomponente necesita un ancla de médula (Paso 1)?", ("Porque la médula no produce señal", "Porque T2*_bm es prácticamente no-identificable a bajo SNR: el prior de médula lo estima desde una ROI y lo congela para el ajuste cortical", "Porque la médula es la señal dominante", "Porque la plataforma lo exige"), 1, "T2*_bm es largo (30-80 ms), persiste en TEs largos donde SNR es bajo, y oscila por chemical shift: el optimizador lo puede fijar en cualquier valor sin degradar el ajuste. El ancla (two-decay water-fat en ROI de médula) lo congela: quedan 5 libres.", f"{D}/marco-teorico/bloque-G-ruido-modelos/T40-prior-medula.md"),
 ("¿Qué es el ancla two-decay water-fat de médula (Paso 1)?", ("Un ajuste mono-exponencial sobre la ROI de médula", "Un modelo de DOS decaimientos con desfase agua-grasa: S_med = S₀·|f_w·e^(-TE/T2*,w) + f_f·e^(-TE/T2*,f)·e^(j2πΔf·TE)|, con f_w + f_f = 1", "Un ajuste tri-componente completo", "Una corrección de B0"), 1, "Es un análisis tipo Dixon: separa agua y grasa por su desfase químico (el mismo Δf≈82 Hz), ajustando la magnitud Rician. Sus dos T2* buscan libres en [30 µs, 300 ms]. Si califica, congelar_ancla_medida congela el T2*_f para el tricomponente.", f"{D}/presentacion-especiales/relaxometria/guion_relaxometria.pdf"),
 ("¿Cuáles son las compuertas de aceptación del ancla?", ("R² > 0.99 y convergencia perfecta", "Converger sin parámetros en el tope del rango + R² ≥ 0.50 sobre la ROI de médula", "R² > 0.95 y sin iteraciones adicionales", "Solo verificar que no hay NaN"), 1, "Dos compuertas: (1) converger sin parámetros pegados al borde (un valor en tope no es una medida, es el límite del optimizador); (2) R² ≥ 0.50. Si el ancla no califica, estrecha a ±50% la ventana del T2*_bm. El mono queda como respaldo legado.", f"{D}/presentacion-especiales/relaxometria/scripts/gen_guion.py"),
 ("¿Por qué no usar el mono-exponencial de médula como ancla (que ya existía)?", ("Porque es más lento", "Porque la médula ONDULA (grasa entra/sale de fase cada 12.2 ms): un modelo que no ondula absorbe esa interferencia como decaimiento aparente, sesgando T2* para justo el uso que más duele: anclar", "Porque no converge", "Porque es incompatible con el modelo Rician"), 1, "La médula es el caso donde el mono-exponencial falla más como ancla: su magnitud ondula (grasa cada 12.2 ms a 82 Hz) y un modelo sin oscilación devuelve un T2* sesgado. El two-decay lleva la oscilación dentro del modelo.", f"{D}/presentacion-especiales/relaxometria/scripts/gen_guion.py"),
 ("¿Qué es stick-breaking y para qué sirve?", ("Una técnica de compresión de datos", "Una reparametrización que garantiza f_bw + f_pw + f_bm = 1 exactamente en todo el dominio de búsqueda, sin proyecciones", "Un método de inicialización del gradiente", "Un algoritmo de clustering"), 1, "En lugar de buscar tres fracciones independientes (y proyectar a cada paso), stick-breaking las parametriza con funciones sigmoidas en un espacio sin restricciones: la suma es exactamente 1 por construcción. El optimizador trabaja en ℝ² sin restricciones.", f"{P}/Content/3_Methods.tex"),
 ("¿En qué rango buscan los T2* de bw y pw y por qué comparten banda?", ("bw en [0.01, 1] ms, pw en [1, 100] ms: fronteras duras", "Ambos en [0.03, 120] ms compartida: se etiquetan canónicamente tras el ajuste (el más rápido es bw)", "bw en [0.1, 10] ms, pw en [10, 1000] ms", "Solo en [0, 50] ms"), 1, "Ambos buscan en la misma banda [0.03, 120] ms: no imponer frontera arbitraria entre pools es defendible. A 0.55 T los T2* se alargan y una frontera calibrada a campo alto podría clasificar mal. Tras el ajuste, se etiquetan por orden de velocidad.", f"{P}/main.pdf"),
 ("¿Qué es la poda de pools nulos por AICc?", ("Eliminar pools con fracción > 50%", "Tras el ajuste, si la evidencia estadística no soporta 3 pools (AICc), se poda el más débil y se re-ajusta con 2 o 1", "Un método de visualización", "Una corrección de movimiento"), 1, "AICc penaliza el número de parámetros: si la mejora del ajuste no justifica el costo de un parámetro adicional, se poda el pool. Con ancla congelada k=5, sin congelar k=6. Si f_short < 5%, el bi-exp degenera a mono-exp. Es selección objetiva, no del usuario.", f"{D}/presentacion-especiales/relaxometria/README.md"),
 ("¿Qué optimizador se usa para el ajuste tricomponente?", ("L-BFGS", "differential_evolution (optimizador global, mantiene población de soluciones)", "Nelder-Mead simple", "Newton exacto"), 1, "El paisaje del funcional tricomponente es multimodal (múltiples mínimos locales por combinaciones de 3 exponenciales con fracciones). Differential evolution es un algoritmo genético que no necesita derivadas y converge al mínimo global.", f"{D}/presentacion-especiales/relaxometria/README.md"),
 ("¿Qué es el ruido Rician y por qué importa a 0.55 T?", ("Un tipo de ruido térmico", "La distribución de la magnitud M = √(S_R² + S_I²) cuando las partes real e imaginaria tienen ruido gaussiano: E[M] ≥ señal verdadera, con sesgo máximo a bajo SNR", "Ruido de cuantización del ADC", "Ruido de Johnson-Nyquist"), 1, "Cuando SNR → 0 (bajo campo), E[M] converge al piso de Rayleigh σ·√(π/2) independientemente de la señal. Ajustar la exponencial pura (ignorando Rician) subestima T2*: los ecos tardíos aparecen por encima de su valor real.", f"{D}/presentacion-especiales/relaxometria/guion_relaxometria.pdf"),
 ("¿Cuáles son los dos estimadores del ajuste Rician?", ("Solo mínimos cuadrados", "LS (mínimos cuadrados sobre la esperanza E_Rice) y MLE (máxima verosimilitud usando la densidad Rician exacta)", "MLE y MAP", "Gradient descent y Newton"), 1, "LS minimiza (M_i − E_Rice(ν_i, σ))²: rápido y robusto, pero asume residuos gaussianos (no se cumple a bajo SNR). MLE maximiza log p(M_i|ν_i, σ): usa la densidad Rician exacta, es asintóticamente óptimo e insesgado a bajo SNR.", f"{D}/presentacion-especiales/relaxometria/main.pdf"),
 ("¿Cómo se estima σ (el parámetro de ruido)?", ("Siempre σ = 1", "Desde una ROI de fondo (aire): σ ≈ STD_ruido, promediado sobre los TEs", "Desde el ajuste mismo", "Del fabricante del escáner"), 1, "σ se estima desde una ROI de fondo: σ ≈ STD_ruido, o equivalentemente σ = M̄_ruido/1.253. Si es similar en todos los ecos (típicamente lo es), se promedia sobre los N_e TEs. Fallback sin fondo: σ ≈ 0.5·STD_tejido.", f"{D}/marco-teorico/bloque-I-procesamiento-metricas/T47-extraccion-roi.md"),
 ("¿Qué es el ECC y por qué es necesario antes del ajuste?", ("Una corrección de B0", "Enhanced Correlation Coefficient: registro rígido (rotación + traslación) de cada imagen de eco contra la referencia del TE más corto, para que el ROI muestre el mismo tejido", "Un método de compresión de datos", "Una corrección de eddy currents"), 1, "Pequeño movimiento del sujeto entre ecos hace que la ROI muestre vóxeles distintos en cada TE, corrompiendo el ajuste. ECC registra rígidamente cada eco al TE más corto (mayor SNR y detalle): 2D Euclidean warp, 10⁴ iteraciones, tolerancia 10⁻¹².", f"{D}/Paper-MRI-US/diseno_images/04_metodo_tricomponente/fig5_tricomponente_relaxometry.pdf"),
 ("¿Cómo se deriva el índice de porosidad (PI) del ajuste tricomponente?", ("PI = S₀ / S_bw", "PI = f_pw = S_pw / (S_bw + S_pw): agua de poro sobre agua cortical, sin contaminación de médula", "PI = f_bm = S_bm / S_total", "PI = T2*_pw / T2*_bw"), 1, "El índice de porosidad PI = f_pw reparte el agua cortical entre sus dos pools: es adimensional, independiente de calibración, comparable entre sujetos. Conecta directamente con la fragilidad: a mayor porosidad, más agua de poro relativa.", f"{D}/presentacion-especiales/relaxometria/guion_relaxometria.pdf"),
 ("¿Por qué las fracciones usan DOS denominadores distintos?", ("Simplificación computacional", "f_bw y f_pw sobre agua cortical (S_bw+S_pw): responden composición; f_bm sobre señal total (S_bw+S_pw+S_bm): responde calidad de la ROI", "Porque hay dos tipos de ajuste", "Por tradición en la literatura"), 1, "Dos denominadores responden dos preguntas distintas: f_bw/f_pw (agua cortical) → composición (cuánta matriz vs poro); f_bm (total) → contaminación (cuánta médula se coló). Ambas son clínicamente relevantes pero independientes.", f"{D}/marco-teorico/bloque-I-procesamiento-metricas/T48-sistema-fracciones.md"),
 ("¿Cómo se validó el pipeline de relaxometría en fantoma?", ("Con un maniquí comercial", "Viales con T2* conocido ajustados con el modelo Rician: la UTE reproduce las referencias GRE con desviaciones de 2.2% y 0.8%", "Simulación Monte Carlo", "Comparación con DXA"), 1, "Curvas de decaimiento T2* de dos viales: la serie UTE reproduce las referencias GRE (secuencia clínica estándar) con desviaciones relativas de solo 2.2% y 0.8%. Si el pipeline estuviera sesgado, las desviaciones serían sistemáticas y mucho mayores.", f"{C}/docs/template-parcial-final-2026-09-19.pdf"),
 ("¿Qué es el prior de frontera BW/PW y cuál es su valor por defecto?", ("La amplitud mínima del ajuste: 100 µs", "T2_BW_PW_SPLIT_US_DEFECTO = 1500 µs: la frontera que separa agua ligada de poro en el etiquetado canónico. Es el prior MÁS influyente del modelo", "El umbral de convergencia: 0.001", "El límite de SNR aceptable: 10"), 1, "En priors.py: T2_BW_PW_SPLIT_US_DEFECTO = 1500 µs (rango editable [300, 5000]). Determina cuál pool es cuál cuando ambos buscan en la misma banda. Se observó T2_bw pegado exactamente aquí en 2 de 3 sujetos de la verificación.", f"{D}/codigo/plataforma/api_modelo_tricomponente/src/priors.py"),
 ("¿Qué significan clínicamente f_bw alto y f_pw alto respectivamente?", ("f_bw alto: hueso joven; f_pw alto: hueso poroso", "f_bw alto: hueso poroso; f_pw alto: hueso joven", "Ambos significan hueso sano", "No tienen significado clínico"), 0, "f_bw alto → mucha agua ligada relativa → matriz orgánica densa, bien mineralizada → hueso joven/sano. f_pw (PI) alto → mucha agua de poro → porosidad elevada → fragilidad, osteoporosis. f_bm alto → ROI contaminada con médula → resultado menos confiable.", f"{D}/presentacion-especiales/relaxometria/guion_relaxometria.pdf"),
 ("¿Qué es el fenómeno de mínimos a TE ≈ 6.1 ms en la señal de médula?", ("Un artefacto de reconstrucción", "La firma física del chemical shift: oposición de fase agua-grasa (1/(2·82 Hz) ≈ 6.1 ms), con recuperación en el in-phase a 12.2 ms", "Un error del ADC", "Un artefacto de movimiento"), 1, "La señal de médula ONDULA: mínimos a TE ≈ 6.1 ms (agua y grasa en oposición: 1/(2·82) ≈ 6.1 ms) y recuperación a TE ≈ 12.2 ms (en fase: 1/82 ≈ 12.2 ms). Verificar estos mínimos en los datos valida que el Δf del modelo es correcto.", f"{C}/docs/template-parcial-final-2026-09-19.pdf"),
]),

# ── Q5: Ruido Rician y estadística del ajuste ──
("Examen Doctoral: Ruido Rician y Estadística del Ajuste T2*", [
 ("¿Cuál es la distribución de la magnitud M cuando las partes real e imaginaria tienen ruido gaussiano independiente?", ("Gaussiana", "Rician (o de Rice)", "Poisson", "Uniforme"), 1, "Si S_R y S_I ~ N(μ, σ²) independientes, la magnitud M = √(S_R² + S_I²) sigue una distribución de Rice. A SNR→0 degenera a Rayleigh; a SNR→∞ tiende a Gaussiana.", f"{D}/marco-teorico/bloque-G-ruido-modelos/README.md"),
 ("¿Cuál es la esperanza de la distribución de Rice y por qué importa?", ("E[M] = señal verdadera ν", "E[M] = σ·√(π/2)·e^(-ν²/2σ²)·[(1+ν²/σ²)·I₀(ν²/2σ²) + (ν²/σ²)·I₁(ν²/2σ²)] ≥ ν: el sesgo de magnitud", "E[M] = 0 siempre", "E[M] = ν + σ"), 1, "La esperanza E[M] ≥ ν siempre: la diferencia es el sesgo de magnitud, más grande cuanto menor el SNR. A SNR→0, E[M] → σ·√(π/2) (piso de Rayleigh). Es la razón de ajustar contra E[M] y no contra la señal determinista ν.", f"{D}/marco-teorico/bloque-G-ruido-modelos/README.md"),
 ("¿Qué funciones de Bessel aparecen en la distribución de Rice?", ("I₀ (orden 0) y I₁ (orden 1)", "J₀ y J₁ (Bessel ordinarias)", "K₀ y K₁ (modificadas de segunda especie)", "No aparecen funciones de Bessel"), 0, "La PDF Rician: p(M|ν,σ) = (M/σ²)·e^(-(M²+ν²)/2σ²)·I₀(M·ν/σ²). La esperanza E[M] involucra I₀ y I₁ (funciones de Bessel modificadas de primera especie, órdenes 0 y 1).", f"{D}/marco-teorico/bloque-G-ruido-modelos/README.md"),
 ("¿Qué pasa con el sesgo de magnitud cuando SNR → 0?", ("Desaparece", "E[M] → σ·√(π/2) (piso de Rayleigh): la magnitud converge al piso independientemente de la señal", "E[M] → 0", "E[M] → ν"), 1, "En el régimen de Rayleigh (SNR→0), E[M] converge al piso σ·√(π/2) ≈ 1.253·σ. La magnitud ya no contiene información sobre la señal: ajustar sin corregir esto subestima T2* porque los ecos tardíos aparecen 'demasiado altos'.", f"{D}/marco-teorico/bloque-G-ruido-modelos/README.md"),
 ("¿Por qué el sesgo de magnitud es crítico a 0.55 T?", ("Porque el ruido térmico es mayor a bajo campo", "Porque M₀ ∝ B₀ es menor: el SNR es limitado y la señal cortical cae rápido al piso de ruido donde el sesgo es máximo", "Porque hay más interferencia electromagnética", "Porque el ADC tiene menos bits"), 1, "A 0.55 T, M₀ ≈ 35% de la de 1.5 T. Con T2* ultracorto del bound water, la señal cae al piso de ruido en pocos ms. En ese régimen el sesgo de magnitud es máximo y ignorarlo sesga T2* sistemáticamente hacia arriba.", f"{D}/presentacion-especiales/relaxometria/guion_relaxometria.pdf"),
 ("En el régimen de alto SNR, ¿cómo se aproxima E[M]?", ("E[M] ≈ ν + σ²/(2ν)", "E[M] ≈ ν·σ", "E[M] ≈ ν²", "E[M] = ν"), 0, "A alto SNR: E[M] ≈ ν + σ²/(2ν). El sesgo σ²/(2ν) es pequeño cuando ν ≫ σ. La aproximación gaussiana del ruido es válida en este régimen, pero no en el de bajo SNR del bound water a 0.55 T.", f"{D}/marco-teorico/bloque-G-ruido-modelos/README.md"),
 ("¿Qué es la distribución chi no central y cuándo aparece?", ("La generalización de Rice para múltiples canales combinados en cuadratura (RSS)", "La distribución del estadístico chi-cuadrado", "Una distribución de Poisson compuesta", "La distribución de la suma de gaussianas"), 0, "Cuando se combinan N canales en cuadratura (root sum of squares, RSS), la magnitud sigue chi no central con 2N grados de libertad. El piso de ruido es ~√(2N)·σ, más alto que el Rician de un solo canal.", f"{C}/codigo/plataforma/api_mapas_t2/src/utils_relajacion.py"),
 ("¿Cómo se despejan σ y N (número efectivo de canales) desde el fondo?", ("No se puede: hay que saber qué reconstrucción se usó", "Con la media y la STD del fondo se despejan ambos sin necesidad de saber la reconstrucción: los datos lo dicen", "Se miden en un fantoma separado", "Se asumen fijos"), 1, "La media y STD del fondo contienen la información suficiente para despejar tanto σ como N efectivo: la media del fondo da el piso (que depende de N) y la STD da σ. No hay que asumir qué reconstrucción se usó (SENSE vs RSS): los datos lo determinan.", f"{C}/codigo/plataforma/api_mapas_t2/src/utils_relajacion.py"),
 ("¿Por qué es importante usar el mismo σ en el ancla y en el ajuste cortical?", ("Porque simplifica el código", "Porque el ruido es el mismo en la misma adquisición: usar σ distinto haría los términos de verosimilitud estadísticamente inconsistentes entre sí", "Porque el fabricante lo exige", "Para reducir el tiempo de cómputo"), 1, "El ancla de médula y el ajuste cortical usan datos de la MISMA adquisición: el σ es idéntico. Usar el mismo σ garantiza que los términos de verosimilitud sean estadísticamente coherentes: la inferencia MAP es consistente entre pasos.", f"{D}/presentacion-especiales/relaxometria/guion_relaxometria.pdf"),
 ("¿Cuál es la estrategia de inicialización secuencial del ajuste multi-exponencial?", ("Sembrar aleatoriamente", "Ajustar mono-exp a los TEs altos para inicializar la componente larga, luego mono-exp al residuo para la corta, y alimentar al optimizador global", "Empezar siempre desde cero", "Usar los valores de la literatura sin ajuste"), 1, "Paso 1: mono-exp a TEs altos (donde BW ya decayó) → inicializa componente larga. Paso 2: mono-exp al residuo → inicializa componente corta. Esta semilla reduce las evaluaciones del differential evolution al colocarlo cerca de la solución.", f"{D}/marco-teorico/bloque-G-ruido-modelos/T38-modelo-biexponencial.md"),
 ("¿Cuántos TEs se muestrean y con qué distribución espacial?", ("6 uniformes", "12 entre 0.03 y 25 ms con distribución logarítmica: cada década de T2* recibe igual número de muestras", "20 uniformes", "3 seleccionados manualmente"), 1, "12 TEs con muestreo logarítmico que cubre toda la dinámica de los tres pools. Diez TEs son suficientes para el ajuste robusto del tricomponente; doce dan margen. La distribución logarítmica optimiza información por dato.", f"{D}/marco-teorico/bloque-A-marco-clinico-anatomico/T04-tres-pools-protones.md"),
 ("¿Qué es el R² de un ajuste y qué valor se exige en el ancla de médula?", ("R² es el error absoluto; se exige > 0.99", "R² es el coeficiente de determinación (1 - SS_res/SS_tot); se exige ≥ 0.50 para el ancla", "R² es la raíz del error cuadrático; se exige < 0.1", "R² no se usa"), 1, "R² = 1 - SS_res/SS_tot mide la fracción de varianza explicada por el modelo. Para el ancla de médula two-decay se exige R² ≥ 0.50: suficiente para confiar en el T2*_f pero no tan estricto como para rechazar anclas clínicamente válidas.", f"{D}/presentacion-especiales/relaxometria/scripts/gen_guion.py"),
]),

# ── Q6: Anatomía y agua en hueso ──
("Examen Doctoral: Anatomía del Hueso Cortical y los Pools de Agua", [
 ("¿Cuáles son los tres pools de protones del hueso cortical?", ("Agua libre, agua difusa, grasa", "Bound water (colágeno), pore water (Havers/lagunas), bone marrow (grasa de médula)", "Cortical, trabecular, medular", "Intracelular, extracelular, vascular"), 1, "BW = agua ligada a la matriz de colágeno (T2* ~50-500 µs). PW = agua en canales de Havers y lagunas (T2* ~1-50 ms). BM = señal de médula/grasa residual con chemical shift (T2* ~30-80 ms). Separación ~100× entre vecinos.", f"{D}/presentacion-especiales/relaxometria/guion_relaxometria.pdf"),
 ("¿Dónde se encuentra el bound water anatómicamente?", ("En la médula ósea", "Asociada a la matriz de colágeno tipo I entre cristales de hidroxiapatita, a escalas nanométricas", "En los vasos sanguíneos", "En el espacio extracelular libre"), 1, "BW está en la interfase colágeno-mineral: agua estructural dentro de la triple hélice y agua en la superficie de los cristales de hidroxiapatita. El confinamiento nanométrico acelera el desfase, resultando en T2* ultracorto.", f"{D}/marco-teorico/bloque-A-marco-clinico-anatomico/T04-tres-pools-protones.md"),
 ("¿Dónde se encuentra el pore water y a qué escalas?", ("Solo en los vasos sanguíneos", "En canales de Havers (~50 µm) y sistemas lacunocaniculares (lagunas ~10 µm, canalículos ~100 nm)", "En la matriz mineral", "En el periostio"), 1, "PW se aloja en dos escalas: canales de Havers (~50 µm, con vasos y nervios) y sistemas lacunocaniculares (lagunas de osteocitos ~10 µm conectadas por canalículos ~100 nm). Es proxy directo de porosidad.", f"{D}/marco-teorico/bloque-A-marco-clinico-anatomico/T04-tres-pools-protones.md"),
 ("¿Qué es un osteón y cuál es su diámetro típico?", ("Una célula ósea de ~1 µm", "La unidad estructural cilíndrica del hueso cortical, ~200 µm de diámetro, organizada alrededor de un canal de Havers", "Un tipo de colágeno", "Una proteína de la matriz"), 1, "El osteón (o sistema de Havers) es la unidad estructural del hueso cortical: un cilindro de ~200 µm de diámetro con laminillas concéntricas alrededor de un canal central de Havers que aloja un vaso sanguíneo.", f"{D}/marco-teorico/bloque-A-marco-clinico-anatomico/T04-tres-pools-protones.md"),
 ("¿Por qué se eligió la tibia media como sitio anatómico?", ("Porque es la más fácil de acceder", "Cortical gruesa y bien definida, accesible superficial (bobina flexible), coincide con el sitio estándar QUS/BDAT, y tiene médula central para el ancla", "Porque es el hueso más largo", "Porque tiene la mayor densidad"), 1, "La tibia media: (1) hueso de carga con cortical gruesa; (2) accesible superficialmente para la bobina; (3) coincide con el estándar QUS; (4) la cara medial plana facilita el transductor BDAT; (5) médula central para el ancla del modelo.", f"{C}/narracion/texto/cap5.txt"),
 ("¿Qué proporción del hueso cortical es mineral y qué orgánica?", ("50% mineral, 50% orgánica", "~70% mineral (hidroxiapatita), ~30% orgánica (mayormente colágeno tipo I)", "~90% mineral, ~10% orgánica", "~30% mineral, ~70% orgánica"), 1, "El hueso cortical es un composite: ~70% inorgánico (Ca₁₀(PO₄)₆(OH)₂, hidroxiapatita) y ~30% orgánico (casi todo colágeno tipo I). El agua ocupa el ~15-20% del volumen con señal detectable por RM.", f"{D}/presentacion-especiales/relaxometria/guion_relaxometria.pdf"),
 ("¿Qué es la porosidad cortical y por qué es importante para la fragilidad?", ("El tamaño del hueso", "La fracción de volumen ocupado por canales de Havers y sistemas lacunocaniculares: determinante directo de la resistencia mecánica", "La densidad mineral", "El espesor del periostio"), 1, "La porosidad cortical es la fracción de volumen con poros: a mayor porosidad, menos material resistente. Es el determinante más directo de la fragilidad. El agua de poro es su proxy en RM: más poros = más PW relativa = mayor PI.", f"{D}/marco-teorico/bloque-A-marco-clinico-anatomico/T04-tres-pools-protones.md"),
 ("La fragilidad ósea se define clínicamente como:", ("La pérdida de densidad mineral", "La pérdida de la capacidad del esqueleto para resistir cargas que un hueso sano tolera, manifestándose como fractura por bajo trauma", "La osteoporosis diagnosticada por DXA", "La edad avanzada"), 1, "La fragilidad ósea es la pérdida de capacidad de resistencia: se manifiesta como fractura por bajo trauma. Es la fractura, no el puntaje densitométrico, la que define la carga de la enfermedad. La osteoporosis es UNA causa entre varias.", f"{C}/narracion/texto/cap2.txt"),
 ("¿Qué evidencia muestra la disociación densidad-riesgo de la DXA?", ("Que la DXA siempre acierta", "La diabetes tipo 2, obesidad y glucocorticoides aumentan fractura sin caída comparable de DMO: >50% de fracturas ocurren con T-score no osteoporótico", "Que la DXA es perfectamente sensible", "Que no hay otra técnica mejor"), 1, "La evidencia clínica: DM2, obesidad y glucocorticoides aumentan riesgo de fractura sin caída comparable de DMO. En DM2 las fracturas ocurren con DMO normal-elevada (mayor porosidad, mineralización anormal, glicación del colágeno).", f"{D}/Paper-MRI-US/narracion/texto/intro.txt"),
 ("¿Qué es el T-score y cuál es el umbral de osteoporosis?", ("El puntaje Z de la población local; umbral -1", "El T-score compara la DMO con el pico de masa ósea adulta joven; osteoporosis se define como T-score ≤ -2.5", "El porcentaje de masa ósea; umbral 70%", "Un marcador bioquímico; umbral 50 ng/mL"), 1, "T-score = (DMO_paciente - DMO_pico_adulto_joven) / DS_pico. Osteoporosis operacional: T-score ≤ -2.5. Pero la evidencia muestra que >50% de fracturas por fragilidad ocurren con T-score > -2.5: hay que mirar más allá de la densidad.", f"{C}/narracion/texto/cap2.txt"),
]),

# ── Q7: Chemical shift y supresión de grasa ──
("Examen Doctoral: Chemical Shift, Supresión de Grasa e IR-UTE", [
 ("¿Por qué la grasa interfiere con la señal del hueso cortical en UTE?", ("Porque la grasa es más abundante que el hueso", "Porque la grasa de la médula resuena a 3.5 ppm del agua y oscila (entra/sale de fase cada 12.2 ms a 82 Hz), interfiriendo con el decaimiento", "Porque la grasa es magnética", "Porque absorbe la señal RF"), 1, "La grasa de la médula adyacente al hueso cortical resuena a Δf ≈ 82 Hz del agua. El fasor de la grasa rota y produce interferencia constructiva/destructiva (rizado) sobre el decaimiento de la señal cortical: mínimos a 6.1 ms y picos a 12.2 ms.", f"{D}/presentacion-especiales/chemical-shift/scripts/gen_guion.py"),
 ("¿Cuál es la primera línea de defensa contra el chemical shift?", ("Suprimir la grasa con saturación espectral", "Evitar ecos en oposición de fase (TE ≠ 6.1 ms ± margen)", "Usar una bobina que no vea médula", "Reducir el FOV"), 1, "La primera línea: evitar los TEs donde agua y grasa están en oposición de fase (TE ≈ 6.1 ms a 0.55 T). Si el tren multi-eco no muestrea esos TEs, la interferencia se minimiza sin modelarla explícitamente.", f"{D}/presentacion-especiales/relaxometria/guion_relaxometria.pdf"),
 ("¿Cuál es la segunda línea de defensa (más elegante)?", ("Suprimir grasa con IR-UTE", "Incorporar el desfase explícitamente en el modelo: el término de médula lleva e^(j2πΔf·TE) y la interferencia entra en las ecuaciones como término conocido", "Reducir el grosor de corte", "Usar mayor resolución"), 1, "La segunda línea: no luchar contra la interferencia sino incorporarla al modelo. M(TE) = |S_bw·e^(-TE/T2*,bw) + S_pw·e^(-TE/T2*,pw) + S_bm·e^(-TE/T2*,bm)·e^(j2πΔf·TE)|: el desfase es un término conocido, no un artefacto a suprimir.", f"{D}/presentacion-especiales/chemical-shift/scripts/gen_guion.py"),
 ("¿Qué es IR-UTE (Inversion Recovery UTE)?", ("Una variante de UTE sin gradiente", "Un protocolo con pulso de inversión que suprime la grasa: invierte la magnetización de la grasa y adquiere UTE cuando la grasa está en el cruce nulo", "UTE con mayor flip angle", "UTE con doble eco"), 1, "IR-UTE aplica un pulso de inversión (180°) que invierte la magnetización de la grasa. La secuencia espera hasta que la grasa cruza por cero (TI apropiado) y entonces adquiere UTE: la señal de grasa es nula en ese instante.", f"{D}/Paper-MRI-US/Others/capitulo7/capitulo7c.tex"),
 ("¿Qué pulso de inversión se probó para IR-UTE en esta tesis?", ("Pulso gaussiano", "Pulso hard y pulso adiabático Silver-Hoult", "Pulso sinc apodizado", "No se usó pulso de inversión"), 1, "Se implementó IR-UTE con dos tipos de pulso de inversión: hard y adiabático Silver-Hoult. Los resultados del capítulo 8 muestran que la supresión de grasa no fue efectiva con ninguno y persistieron artefactos de inhomogeneidad a 0.55 T.", f"{C}/narracion/texto/cap8.txt"),
 ("¿Por qué la supresión de grasa es difícil en UTE a bajo campo?", ("Porque la grasa no existe a 0.55 T", "Porque el chemical shift (82 Hz) es menor que a campo alto: las técnicas espectrales tienen menos margen y la B1-inhomogeneidad a 0.55 T es mayor", "Porque la UTE no soporta pulsos de inversión", "Porque el SAR lo impide"), 1, "A 0.55 T, Δf = 82 Hz es mucho menor que a 3 T (~440 Hz): las técnicas de saturación espectral selectiva tienen menos margen espectral. Además, la B1-inhomogeneidad es mayor a bajo campo, haciendo los pulsos de inversión menos homogéneos.", f"{C}/narracion/texto/cap8.txt"),
 ("¿Qué es UTE-hmrGC y cómo complementa el modelo tricomponente?", ("Un método de reconstrucción", "Hierarchical multi-resolution Graph Cut: separa agua/grasa con mapas de PDFF, R2* y B0, y sirve como validación cruzada del f_bm del tricomponente", "Un tipo de bobina", "Un protocolo de adquisición"), 1, "UTE-hmrGC (sobre fieldmapping-hmrGC de Stelter 2022) genera mapas water-only/fat-only, PDFF, R2* y B0. Si el mapa PDFF concuerda con la fracción f_bm del tricomponente, la cuantificación es coherente entre dos métodos independientes.", f"{C}/anexos/anexo5.tex"),
 ("¿Por qué se usan ecos en fase (12.2 ms) en el tren multi-eco?", ("Porque tienen mayor SNR", "Porque en el in-phase (TE = 1/Δf ≈ 12.2 ms) agua y grasa están alineadas: la señal de médula es máxima y sirve para estimar mejor el ancla", "Porque evitan el aliasing", "Porque es un requisito del fabricante"), 1, "A TE = 12.2 ms (in-phase a 0.55 T): agua y grasa están en fase, la señal de médula es máxima y no hay cancelación. Incluir este TE en el tren mejora la estimación del ancla de médula (T2*_bm) porque la señal de grasa no está suprimida por interferencia.", f"{C}/docs/template-parcial-final-2026-09-19.pdf"),
]),

# ── Q8: US-BDAT ──
("Examen Doctoral: US-BDAT y Comparación Multimodal", [
 ("¿Qué es BDAT (Bidirectional Axial Transmission)?", ("Una técnica de radiografía", "Un método de ultrasonido que mide ondas guiadas en la corteza ósea transmitiendo en ambas direcciones a lo largo del hueso", "Un tipo de RM", "Un biomarcador bioquímico"), 1, "BDAT transmite ultrasonido en ambas direcciones a lo largo del hueso cortical. La geometría bidireccional elimina el retardo del tejido blando (mide la diferencia de tiempo de llegada de las ondas en ambas direcciones).", f"{C}/narracion/texto/anexo6.txt"),
 ("¿Por qué la corteza ósea se comporta como una guía de ondas?", ("Porque es plana", "Porque su espesor es comparable a la longitud de onda del ultrasonido (200-500 kHz): las ondas se propagan por modos guiados cuya velocidad depende del espesor", "Porque es rígida", "Porque contiene agua"), 1, "Cuando el espesor cortical ≈ λ del ultrasonido, se forman modos guiados (Lamb waves). La velocidad de estos modos depende del espesor y de las propiedades elásticas: midiendo la velocidad se infiere espesor y porosidad.", f"{C}/narracion/texto/anexo6.txt"),
 ("¿Qué sitios anatómicos mide BDAT vs UTE-MRI en esta tesis?", ("BDAT solo en tibia; UTE en todo el cuerpo", "BDAT en tibia Y radio izquierdos; UTE-MRI solo en tibia media izquierda: la comparación sitio-a-sito ocurre en la tibia", "Ambos en los mismos 4 sitios", "BDAT en columna; UTE en cadera"), 1, "UTE-MRI se aplica en la diáfisis tibial media izquierda. BDAT se mide en ambos (tibia y radio) izquierdos. La comparación multimodal emparejada por sitio ocurre en la diáfisis tibial media, donde ambas técnicas describen la misma región cortical.", f"{D}/Paper-MRI-US/narracion/texto/methods.txt"),
 ("¿Cómo se extraen espesor y porosidad de las mediciones BDAT?", ("Directamente del transductor", "De las curvas de dispersión experimentales (velocidad vs frecuencia) mediante ajuste al modelo de guía de ondas (problema inverso)", "De la amplitud de la señal", "Del tiempo de vuelo únicamente"), 1, "El problema inverso BDAT: de las curvas de dispersión (velocidad de fase vs frecuencia de los modos guiados), se estiman espesor cortical y porosidad ajustando al modelo teórico de guía de ondas. Es la ruta US hacia los mismos biomarcadores que UTE mide por RM.", f"{C}/narracion/texto/anexo6.txt"),
 ("¿Cuál es la ventaja de comparar UTE-MRI y BDAT emparejados por sitio?", ("Es más rápido", "El propio sitio es su control: se elimina la variabilidad inter-sujeto que ahogaría el efecto en un diseño no emparejado", "Es más barato", "Reduce el SAR"), 1, "En un diseño emparejado por sitio, cada sitio anatómico se mide con ambas técnicas en la misma sesión: el propio sitio es su control. La diferencia entre técnicas se evalúa sin el ruido de la variabilidad anatómica entre sujetos.", f"{D}/Paper-MRI-US/narracion/texto/methods.txt"),
 ("¿Qué ventaja tiene BDAT frente a DXA para calidad ósea?", ("BDAT mide densidad", "BDAT mide propiedades elásticas y geométricas de la corteza (espesor, porosidad vía velocidad de ondas) que la densidad DXA no captura, y sin radiación", "BDAT es más preciso que DXA", "BDAT es más barato"), 1, "BDAT mide la velocidad de propagación de ondas guiadas que depende del módulo elástico y la geometría cortical (espesor): propiedades mecánicas que la DXA (proyección areal de densidad) estructuralmente no puede capturar. Además, sin radiación ionizante.", f"{C}/narracion/texto/anexo6.txt"),
 ("¿Cuántos pares RM-BDAT emparejados se han adquirido a la fecha?", ("5", "10", "15", "20"), 2, "A la fecha (septiembre 2026) se han adquirido quince pares de mediciones RM-BDAT emparejadas por sitio. La campaña de mediciones in vivo RM-UTE y US-BDAT cierra en septiembre de 2026 con N=20 sujetos.", f"{C}/narracion/texto/cap7.txt"),
 ("¿Qué son los modelos A y B de regresión en la comparación UTE-BDAT?", ("Dos versiones del software", "Dos modelos estadísticos planificados para evaluar la relación entre biomarcadores UTE (fracciones, PI) y métricas BDAT (velocidad, atenuación)", "Dos protocolos de adquisición", "Dos tipos de ajuste exponencial"), 1, "Los Modelos A y B son dos especificaciones de regresión planificadas para relacionar los biomarcadores UTE (fracciones f_bw, f_pw, PI) con las métricas BDAT (velocidad de propagación, atenuación): evalúan si ambas rutas convergen en los mismos biomarcadores.", f"{C}/docs/planificacion-parcial-final.md"),
]),

# ── Q9: Fragilidad, DXA y calidad ósea ──
("Examen Doctoral: Fragilidad Ósea, DXA y Calidad Ósea", [
 ("¿Qué es la calidad ósea y qué componentes integra?", ("Solo la densidad mineral", "Densidad + microarquitectura (porosidad) + composición de matriz (colágeno, glicación) + mineralización + geometría", "Solo la geometría", "Solo el colágeno"), 1, "Calidad ósea = densidad + microarquitectura + composición de matriz + mineralización + geometría macroscópica. La DXA solo mide densidad areal: deja fuera los demás componentes que determinan fragilidad.", f"{C}/narracion/texto/cap2.txt"),
 ("¿Cuál es el aporte del hueso cortical a la resistencia mecánica del esqueleto?", ("10%", "30%", "50%", "80%"), 3, "El hueso cortical aporta el 80% de la resistencia mecánica del esqueleto. Su deterioro (aumento de porosidad en Havers y lacunocaniculares) precede a la pérdida de DMO areal que la DXA detecta tardíamente.", f"{C}/narracion/texto/cap2.txt"),
 ("¿En la diabetes tipo 2, por qué aumentan las fracturas con DMO normal?", ("Porque los diabéticos se caen más", "Porque hay mayor porosidad cortical, mineralización anormal y glicación del colágeno: cambios de calidad ósea no capturados por DMO areal", "Porque tienen osteoporosis diagnosticada erróneamente", "Porque toman metformina"), 1, "En DM2 las fracturas ocurren a pesar de DMO normal-elevada, reflejando: mayor porosidad cortical, mineralización anormal del colágeno, y glicación avanzada (AGEs) que altera las propiedades mecánicas de la matriz sin cambiar la densidad.", f"{D}/Paper-MRI-US/narracion/texto/intro.txt"),
 ("¿Qué porcentaje de fracturas por fragilidad ocurre con T-score no osteoporótico?", ("10%", "25%", "Más del 50%", "95%"), 2, "Más de la mitad de las fracturas por fragilidad ocurren en individuos con T-score por encima del umbral osteoporótico (-2.5). Esta es la evidencia más fuerte de que la densidad sola no basta: hay que medir calidad.", f"{D}/Paper-MRI-US/narracion/texto/intro.txt"),
 ("¿Por qué la tesis busca biomarcadores sin radiación ionizante?", ("Porque es más barato", "Porque permite estudios longitudinales y en poblaciones jóvenes sin el riesgo de radiación acumulada de DXA/CT", "Porque la ética lo prohíbe", "Porque no hay acceso a DXA"), 1, "Sin radiación ionizante: permite seguimiento longitudinal (mediciones repetidas sin dosis acumulada) y estudios en poblaciones jóvenes. Tanto RM-UTE como US-BDAT son técnicas sin radiación, a diferencia de DXA (rayos X) y HR-pQCT (CT).", f"{C}/docs/qa/abstract_p3.png"),
 ("¿Qué son los biomarcadores de porosidad que la tesis deriva?", ("Solo el T2* promedio", "Las fracciones f_bw, f_pw (índice de porosidad) del modelo tricomponente y los índices PI₁ (dual-eco) y PI₂ (model-based)", "Solo el espesor cortical", "La velocidad de ondas guiadas"), 1, "Los biomarcadores: f_bw (fracción de agua ligada, proxy de matriz), f_pw/PI (fracción de agua de poro, proxy de porosidad), PI₁ (dual-eco, screening rápido) y PI₂ (model-based, desde el ajuste completo). Son adimensionales, comparables entre sujetos.", f"{C}/narracion/partes/cap5/par_015.txt"),
 ("¿Qué validación ética tiene el estudio?", ("No requiere aprobación", "Aprobación ética de la Universidad de Valparaíso y protocolo de RM iHEALTH de la PUC, ID 210125006", "Solo consentimiento informado", "Aprobación del fabricante Siemens"), 1, "El estudio tiene aprobación ética de la Universidad de Valparaíso y protocolo de RM iHEALTH de la Pontificia Universidad Católica de Chile (ID 210125006). Cohorte N=20, mediciones cierran en septiembre de 2026.", f"{C}/narracion/texto/cap7.txt"),
 ("¿Cuáles son los criterios de exclusión del estudio in vivo?", ("Solo el embarazo", "IMC > 35 kg/m² (posicionamiento de bobina), implantes metálicos no compatibles con RM, claustrofobia o incapacidad de estar quieto ~10 min", "Solo la edad > 80", "Diabetes y osteoporosis diagnosticada"), 1, "Exclusión: IMC > 35 kg/m² (para asegurar posicionamiento correcto de la bobina flexible), implantes no compatibles con RM, claustrofobia o incapacidad de tolerar el examen (~10 min por adquisición).", f"{D}/Paper-MRI-US/Content/3_Methods/3.4_In_Vivo_Feasibility.tex"),
 ("¿Qué rango de edad tienen los voluntarios del estudio?", ("20-50 años", "20-80 años", "50-90 años", "30-60 años"), 1, "Voluntarios sanos de 20 a 80 años, sin patologías óseas diagnosticadas. Este amplio rango etario permite evaluar si los biomarcadores UTE detectan cambios de porosidad asociados al envejecimiento normal.", f"{D}/Paper-MRI-US/Content/3_Methods/3.4_In_Vivo_Feasibility.tex"),
 ("¿Cuál es la contribución original de esta tesis según el paper?", ("Una nueva secuencia UTE", "La primera cuantificación tri-componente in vivo de agua en hueso cortical a 0.55 T con modelo consciente de médula y comparador US sin radiación", "Una nueva técnica de DXA", "Un nuevo biomarcador bioquímico"), 1, "We present, to our knowledge, the first in vivo tri-component T2* quantification of cortical bone water at 0.55 tesla, combining an ultrashort-echo-time radial sequence with a marrow-aware signal model and a radiation-free ultrasound comparator.", f"{D}/Paper-MRI-US/narracion/texto/discussion.txt"),
]),

# ── Q10: Simulacro general ──
("Simulacro Doctoral: Integración Completa MRI-UTE + CS + Tricomponente + BDAT", [
 ("¿Cuál es el TE mínimo de la secuencia UTE de esta tesis?", ("50 µs", "30 µs, medido del fin del RF a la primera muestra del ADC", "100 µs", "1 ms"), 1, "TE = 30 µs desde el fin del pulso RF hasta la primera muestra del ADC. Es el parámetro crítico que define si la señal de T2* ultracorto es capturada antes de decaer. Se logra con half pulse VERSE + ramp sampling.", f"{C}/anexos/anexo2.tex"),
 ("¿Cuántos TEs muestrea el tren multi-eco y en qué rango?", ("6 TEs de 1 a 10 ms", "12 TEs de 0.03 a 25 ms con distribución logarítmica", "24 TEs de 0 a 50 ms", "3 TEs seleccionados manualmente"), 1, "12 TEs entre 0.03 y 25 ms: muestreo logarítmico que cubre toda la dinámica de los tres pools (BW ~0.4 ms, PW ~4 ms, BM ~40 ms). Diez TEs son suficientes para el ajuste robusto.", f"{D}/marco-teorico/bloque-A-marco-clinico-anatomico/T04-tres-pools-protones.md"),
 ("¿Cuál es el valor de λ en la reconstrucción CS de esta tesis?", ("λ = 1", "λ = 0.1", "λ = 10⁻⁴", "λ = 10⁻⁸"), 2, "λ = 10⁻⁴ es el peso del regularizador TV en el funcional (1/2)‖Ex−y‖² + λ·TV(x). Calibrado en fantoma y validado con métricas pareadas SSIM.", f"{C}/main.pdf"),
 ("¿Cuántas iteraciones usa el solver ADMM de la reconstrucción CS?", ("10", "25", "50", "100"), 2, "ADMM corre 50 iteraciones: repite pequeñas correcciones hasta que la imagen cumple consistencia con los datos + suavidad por tramos. TV no es diferenciable y ADMM la maneja con su operador proximal.", f"{C}/main.pdf"),
 ("¿Cuál es el factor de submuestreo CS máximo soportado por el protocolo?", ("2× (factor 0.5)", "3× (factor 0.33)", "5× (factor 0.2)", "10× (factor 0.1)"), 2, "cs_undersampling_factor ∈ [0.2, 1.0]: de 1× (Nyquist completo) a 5× (20% de muestras). Con 5×, un protocolo de ~785 TRs se reduce a ~157: viabilidad clínica.", f"{D}/marco-teorico/bloque-F-reconstruccion/T31-compressed-sensing.md"),
 ("¿Cuál es el Δf del chemical shift agua-grasa a 0.55 T?", ("42 Hz", "58 Hz", "82 Hz (3.5 ppm × 42.577 MHz/T × 0.55 T = 81.96 Hz)", "120 Hz"), 2, "Δf = 3.5 ppm × γ × B₀ = 3.5×10⁻⁶ × 42.577×10⁶ × 0.55 = 81.96 Hz ≈ 82 Hz. Produce mínimos a TE ≈ 6.1 ms (oposición) y recuperación a 12.2 ms (in-fase).", f"{D}/codigo/plataforma/api_modelo_tricomponente/src/priors.py"),
 ("¿Cuántos parámetros libres quedan en el ajuste tricomponente con el ancla congelada?", ("3", "4", "5: θ = {S₀, f_bw, f_pw, T2*,bw, T2*,pw}", "7"), 2, "Con el T2*_bm congelado del ancla, quedan 5 libres: S₀, f_bw, f_pw, T2*,bw, T2*,pw (con f_bm = 1 - f_bw - f_pw). AICc k=5. Sin congelar k=6.", f"{P}/main.pdf"),
 ("¿Cuál es la función que implementa el modelo tricomponente en el código?", ("relaxometry.py", "RelajacionTransversal en relajacionTransversalTri.py", "fit.py", "model.py"), 1, "La clase RelajacionTransversal en relajacionTransversalTri.py implementa mono-exp Rician (LS y MLE) y 3-componentes + chemical shift. Con tipo_tejido='cortical' separa BW, PW y BM.", f"{C}/codigo/plataforma/api_modelo_tricomponente/src/relajacionTransversalTri.py"),
 ("¿Cuál es el R² mínimo exigido por el ancla de médula?", ("> 0.99", "> 0.95", "≥ 0.50", "> 0.10"), 2, "R² ≥ 0.50 para aceptar el ancla two-decay: suficiente para confiar en el T2*_f sin ser tan estricto como para rechazar anclas clínicamente válidas. Si no califica, estrecha a ±50% la ventana.", f"{D}/presentacion-especiales/relaxometria/scripts/gen_guion.py"),
 ("¿Qué porcentaje de desviación se logró en la validación en fantoma?", ("< 0.1%", "2.2% y 0.8% (vs referencias GRE)", "10%", "25%"), 1, "Viales con T2* conocido: la serie UTE reproduce las referencias GRE con desviaciones relativas de 2.2% y 0.8%. Valida que toda la cadena (adquisición → CS → ajuste Rician) es cuantitativamente correcta.", f"{C}/docs/template-parcial-final-2026-09-19.pdf"),
 ("¿Cuántos servicios docker levanta la plataforma de la tesis?", ("5", "10", "15", "20"), 2, "Un único docker compose up levanta los quince servicios: rawdata-api, reconstruction-api, api_mapas_t2, api_modelo_tricomponente, frontend, PostgreSQL, MongoDB, Parse, y más. La función es de soporte: hace el estudio reproducible de punta a punta.", f"{C}/anexos/anexo7.tex"),
 ("¿Qué resonador se usa y con qué campo?", ("1.5 T Philips", "0.55 T Siemens MAGNETOM Free.Max de cuerpo completo", "3 T Siemens Skyra", "0.3 T Siemens Magnetom"), 1, "MAGNETOM Free.Max (Siemens Healthineers) de 0.55 T: resonador de cuerpo completo de bajo campo. Sin helio (o consumo reducido). Con bobina flexible de extremidad para maximizar señal cerca de la tibia.", f"{C}/capitulos/capitulo4.tex"),
 ("¿Cuál es el número de sujetos del estudio y su rango de edad?", ("N=10, 30-60 años", "N=20, 20-80 años", "N=50, 40-70 años", "N=100, 18-90 años"), 1, "N=20 voluntarios sanos, edad 20-80 años. Aprobación ética UV + PUC (ID 210125006). Campaña cierra septiembre 2026. Quince pares RM-BDAT ya adquiridos.", f"{D}/Paper-MRI-US/Content/3_Methods/3.4_In_Vivo_Feasibility.tex"),
 ("¿Qué framework se usa para la reconstrucción CS?", ("MATLAB", "TensorFlow-MRI (tfmri): NUFFT, sensibilidades, optimizadores proximales", "PyTorch + SigPy", "C++ con ITK"), 1, "TensorFlow-MRI expone la NUFFT, operadores de sensibilidad y optimizadores proximales como bloques componibles. El mismo pipeline corre en simulación y en la campaña in vivo.", f"{C}/docs/template-parcial-final-2026-09-19.pdf"),
 ("¿Qué es Pypulseq y por qué se eligió para la secuencia UTE?", ("Un simulador de RM", "Framework open-source Python que compila secuencias a archivo .seq ejecutable por escáneres Siemens, sin programar en IDEA propietario", "Una librería de reconstrucción", "Un tipo de bobina"), 1, "Pypulseq permite definir programáticamente pulsos RF, gradientes y ADC que se compilan a .seq. Ventaja: open-source, reproducible, un mismo núcleo científico sirve a simulación (KomaMRI) y escáner real.", f"{C}/narracion/texto/anexo2.txt"),
 ("¿Cuál es el índice de porosidad (PI) y cómo se calcula?", ("PI = S₀/(S_bw+S_pw+S_bm)", "PI = f_pw = S_pw/(S_bw + S_pw): agua de poro sobre agua cortical sin contaminación de médula", "PI = T2*_pw × f_pw", "PI = S_bm/S_total"), 1, "PI = f_pw reparte el agua cortical entre sus dos pools. Es adimensional, independiente de calibración, comparable entre sujetos. Conecta con la fragilidad: a mayor porosidad, más PW relativa.", f"{D}/presentacion-especiales/relaxometria/guion_relaxometria.pdf"),
 ("¿Cuál es el optimizador del ajuste tricomponente?", ("L-BFGS", "differential_evolution (algoritmo genético, global, sin derivadas)", "Nelder-Mead", "Adam"), 1, "Differential evolution: mantiene una población de soluciones candidatas, las combina por recombinación y selección, converge al mínimo global sin derivadas. Necesario porque el paisaje tricomponente es multimodal.", f"{D}/presentacion-especiales/relaxometria/README.md"),
 ("¿En qué año se planea que cierre la campaña de mediciones?", ("2025", "2026 (septiembre)", "2027", "Ya cerró"), 1, "La campaña de mediciones in vivo RM-UTE y US-BDAT cierra en septiembre de 2026. El cronograma del proyecto: 24 meses, mes 1 = marzo 2025, actualmente en el mes 19 de 24.", f"{C}/narracion/texto/cap6.txt"),
 ("¿Qué valide la presentación especial de relaxometría?", ("Solo el modelo mono-exponencial", "Los 7 pasos del pipeline: glosario, problema, Rician, mono-exp, por qué tri, modelo con CS, ancla, fracciones y 7 preguntas de defensa", "Solo la anatomía", "Solo la plataforma"), 1, "La presentación especial de relaxometría cubre todo el pipeline con preguntas de defensa resueltas: P1 (por qué UTE+bajo campo), P2 (Rician), P6 (chemical shift), P7 (prior médula). Es la preparación mínima para el bloque de relaxometría.", f"{D}/presentacion-especiales/relaxometria/guion_relaxometria.pdf"),
 ("La cadena conceptual de la tesis conecta: fractura → DXA límite → calidad ósea → ¿qué sigue?", ("→ tratamiento → cura", "→ pools de agua → tibia → UTE 0.55T → CS → tricomponente → biomarcadores; y BDAT converge → concordancia por sitio", "→ más DXA → medicación", "→ ejercicio → prevención"), 1, "La cadena: fractura/DXA → calidad ósea → tibia → pools de agua → UTE 0.55T → CS → tricomponente → fracciones/PI → biomarcadores. En paralelo: BDAT → ondas guiadas → espesor/porosidad. Ambas convergen en concordancia emparejada por sitio.", f"{C}/capitulos/capitulo2.tex"),
]),
]

# ════════════════════════════════════════════════════════════════════════
# DECKS (20 × 10 tarjetas)
# ════════════════════════════════════════════════════════════════════════
# formato: (título, [(frente, reverso, archivo)])

DECKS = []),
]


async def main():
    async with SessionLocal() as db:
        tema = await db.get(Tema, TEMA)
        print(f"tema: {tema.nombre if tema else '??'}")
        hoy = date.today()

        # ── Quizzes ──
        print("Generando quizzes…")
        nq = 0
        for titulo, preguntas in QUIZZES:
            es_simulacro = "Simulacro" in titulo
            quiz = Quiz(
                titulo=titulo,
                tipo="simulacro" if es_simulacro else "quiz",
                tema_id=TEMA,
                estado="listo",  # ya generado: no necesita LLM
                duracion_min=30 if es_simulacro else 0,
            )
            db.add(quiz)
            await db.flush()
            for i, (enunciado, alts, correcta, explicacion, archivo) in enumerate(preguntas, 1):
                db.add(Pregunta(
                    quiz_id=quiz.id, n=i, enunciado=enunciado,
                    alternativas=alts, correcta=correcta,
                    explicacion=explicacion,
                    cita={"archivo": archivo, "pagina": ""},
                ))
            nq += len(preguntas)
            print(f"  ✓ {titulo} ({len(preguntas)} preguntas)")
        await db.commit()
        print(f"Total preguntas insertadas: {nq}")

        # ── Decks ──
        print("Generando decks…")
        nd = 0
        for titulo, tarjetas in DECKS:
            deck = Deck(titulo=titulo, tema_id=TEMA, estado="listo")
            db.add(deck)
            await db.flush()
            for frente, reverso, archivo in tarjetas:
                db.add(Flashcard(
                    deck_id=deck.id, frente=frente, reverso=reverso,
                    cita={"archivo": archivo, "pagina": ""},
                    proxima_repaso=hoy,
                ))
            nd += len(tarjetas)
            print(f"  ✓ {titulo} ({len(tarjetas)} tarjetas)")
        await db.commit()
        print(f"Total tarjetas insertadas: {nd}")

        # Resumen
        quizzes = (await db.execute(select(Quiz).where(Quiz.tema_id == TEMA))).scalars().all()
        decks = (await db.execute(select(Deck).where(Deck.tema_id == TEMA))).scalars().all()
        print(f"\nRESUMEN: {len(quizzes)} quizzes, {len(decks)} decks en el tema {tema.nombre}")

asyncio.run(main())
